simulation:
  time_seconds: 600     # длительность моделирования, сек
  step_seconds: 1       # шаг снимков нагрузки (snapshots), сек
  seed: 42

traffic:
  base_rps: 1000         # средняя интенсивность поступления сессий (λ)
  users_amount: 450000   # размер пула уникальных пользователей (sessionID)

# сценарий всплесков нагрузки
spikes:
  - at: 120             # t = 120 с
    duration: 30        # 30 с
    factor: 3           # *3 от base_rps
  - at: 300
    duration: 60
    factor: 10
  - at: 450
    duration: 40
    factor: 7

cluster:
  servers: 35             # число серверов в кластере
  bitrate: 10             # Mbps: битрейт одного Full-HD потока
  cap_mean_mbps: 300      # средняя пропускная способность сервера
  cap_cv: 0.3             # CV (σ/μ) пропускной способности
  owd_mean: 300           # средний one-way delay, мс
  owd_cv: 0.15            # CV задержки
  sigma_server: 0.25      # CV лог-нормального шума
  max_retries: 2          # макс кол-во запросов одного и того же .ts-сегмента
  retries_backoff: 100    # задержка между попытками запросов .ts-сегментов
  max_switches: 2         # макс кол-во перебросов с "домашнего" сервера
  switch_penalty: 200     # штраф (мс) при смене сервера
  first_pick_retries: 1   # количество попыток начать сессию
  first_pick_backoff: 200 # интервал для следующего запроса на начало сессии
  

jitter:
  tick_s: 1             # период обновления OWD, сек
  spike_prob: 0.005     # вероятность «лаг-спайка» на каждом тике
  spike_extra: 1000      # +мс к OWD при спайке
  spike_duration_s: 10   # длительность сетевого спайка, сек

balancer:
  strategy: "ch"        # базовый алгоритм (например: rr, random, ch, ch+wlc …)
  ch_replicas: 1000      # количество виртуальных серверов для согласованного хеширования