simulation:
  time_seconds: 600     # длительность моделирования, сек
  step_seconds: 1       # шаг снимков нагрузки (snapshots), сек
  seed: 42

traffic:
  base_rps: 300         # средняя интенсивность поступления сессий (λ)
  users_amount: 50000   # размер пула уникальных пользователей (sessionID)

# сценарий всплесков нагрузки («бурстов»)
spikes:
  - at: 120             # t = 120 с
    duration: 30        # 30 с
    factor: 3           # *5 от base_rps
  - at: 300
    duration: 60
    factor: 8
  - at: 450
    duration: 40
    factor: 5

cluster:
  servers: 30           # число серверов в кластере
  bitrate: 4            # Mbps: битрейт одного Full-HD потока
  cap_mean_mbps: 500    # средняя пропускная способность сервера
  cap_cv: 0.3           # CV (σ/μ) пропускной способности
  owd_mean: 200         # средний one-way delay, мс
  owd_cv: 0.5           # CV задержки
  sigma_server: 0.25    # CV лог-нормального шума
  max_retries: 2        # макс кол-во запросов одного и того же .ts-сегмента
  max_switches: 4        # макс кол-во перебросов с "домашнего" сервера

jitter:
  tick_s: 1             # период обновления OWD, сек
  spike_prob: 0.005     # вероятность «лаг-спайка» на каждом тике
  spike_extra: 400      # +мс к OWD при спайке
  spike_duration_s: 5   # длительность сетевого спайка, сек

balancer:
  strategy: "ch"        # базовый алгоритм (например: rr, random, ch, ch+wlc …)
  ch_replicas: 100